version: "1"

services:
  db:
    image: mysql:${DB_VERSION}
    container_name: "${APP_NAME}_db"
    ports:
      - "${DB_PORT}:3306"
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - TZ=${APP_TIMEZONE}